# Hyperparameter
train_dataset: "train-clean-100"
num_workers: 6
batch_size: 4
cepstral_norm: true
resume_training: true

epochs: 8
learning_rate: 0.001 
weight_decay: 0.005  
tf_rate: 0.9
tf_decay_factor: 1.0