# Hyperparameter
train_dataset: "train-clean-100"
num_workers: 6
batch_size: 64
cepstral_norm: true
resume_training: true

epochs: 100
learning_rate: 0.0003
weight_decay: 0.0001  # 과적합 방지
tf_rate: 0.9
tf_decay_factor: 0.98

project_name: "after_pblstm"