# Hyperparameter
## data
train_dataset: "train-clean-100"
num_workers: 6
batch_size: 32
cepstral_norm: true

## data_augmentation
data_augmentation: true
starting_epoch: 60
time_masking: 30
freq_masking: 15

## model
listener_hidden_size: 128
embed_dim: 128

## training
epochs: 100
learning_rate: 0.0005
weight_decay: 0.0001  # 과적합 방지
tf_rate: 1.0
tf_decay_factor_1: 0.99  # stage1(epoch 40이하, alignment 유도 지점)
tf_decay_factor_2: 0.98 # stage2(epoch 40이상, 자립 단계)


project_name: "modify embed_dim"
resume_training: false